### ISSUE TITLE
Capture multiple hearings per case id

### ISSUE THREAD

**Issue by jtcasper** [open-austin/eviction-hearing-parser#16]
Can format with case id + "H0", "H1", "H2", ...

**Comment by jtcasper** [comment]
Could also potentially be 
case id,hearing #
J1-CV-20-XXXXXXX, H0
J1-CV-20-XXXXXXX, H1

**Comment by mscarey** [comment]
I can understand how this would work in JSON, but what happens in a CSV? Is each hearing a separate row, with the case_id and hearing number concatenated together to make a unique ID for the row?

**Comment by jtcasper** [comment]
That's the format Aaron mentioned they had some experience handling. It was a little more difficult for me to hack that than what I've got in my current branch for this, which just has a hearing_number column.

**Comment by mscarey** [comment]
This feature was added in d07d064d991605e50ebf39f4f8b537f5cd42f010 from #20
