### ISSUE TITLE
Determine flow for separating case details and hearing information

### ISSUE THREAD

**Issue by jtcasper** [open-austin/eviction-hearing-parser#26]
>3) For hearings, or any data where there is multiple records per case, would it be possible to have a separate csv that has those cases and have the case # and each hearing's info on a separate line - if it is too hard we can do it after the fact but we will need to separate out the data to normalize it to be able to analyze it so if we can get it that way that would be better - I can also explain more if that is helpful."

**Comment by mscarey** [comment]
Per Aaron's clarification, the request here is for the parser to output two CSV files that are basically like tables in a SQL database. One table has a row for each case, and the other table has a row for each hearing (with a case number column to support join operations).

So, if this is the format that @jtcasper's fork currently provides for multiple hearings in one case:
```
appeared,case_number,defendant_zip,defendants,disposition_amount,disposition_type,disposition_winning_party,hearing_date,hearing_number,hearing_officer,hearing_time,plaintiff,plaintiff_zip,precinct_number,register_url,status,style
True,J1-CV-20-000059,78753,"Doe, and All Other Occupants, John",,Nonsuited/Dismissed by Plaintiff,N/A,01/27/2020,0,"Williams, Yvonne M.",10:00 AM,Residence Estates. L.L.C.,78753,1,https://odysseypa.traviscountytx.gov/JPPublicAccess/CaseDetail.aspx?CaseID=2267317,Dismissed,"Residence Estates. L.L.C. vs. John Doe, and All Other Occupants"
True,J1-CV-20-000059,78753,"Doe, and All Other Occupants, John",,Nonsuited/Dismissed by Plaintiff,N/A,02/03/2020,1,"Williams, Yvonne M.",2:30 PM,Residence Estates. L.L.C.,78753,1,https://odysseypa.traviscountytx.gov/JPPublicAccess/CaseDetail.aspx?CaseID=2267317,Dismissed,"Residence Estates. L.L.C. vs. John Doe, and All Other Occupants"
```

Then this issue asks us to enable this new format:
**Table 1**
```
case_number,defendant_zip,defendants,disposition_amount,disposition_type,disposition_winning_party,plaintiff,plaintiff_zip,precinct_number,register_url,status,style
J1-CV-20-000059,78753,"Doe, and All Other Occupants, John",,Nonsuited/Dismissed by Plaintiff,N/A,Residence Estates. L.L.C.,78753,1,https://odysseypa.traviscountytx.gov/JPPublicAccess/CaseDetail.aspx?CaseID=2267317,Dismissed,"Residence Estates. L.L.C. vs. John Doe, and All Other Occupants"
```

**Table 2**
```
appeared,case_number,hearing_date,hearing_number,hearing_officer,hearing_time,plaintiff,plaintiff_zip,precinct_number,register_url,status,style
True,J1-CV-20-000059,01/27/2020,0,"Williams, Yvonne M.",10:00 AM,
True,J1-CV-20-000059,02/03/2020,1,"Williams, Yvonne M.",2:30 PM,
```

**Comment by mscarey** [comment]
@jtcasper Assuming we want the ability to put this data in a database with two tables, do we want the database interface to be part of the utility, or should the utility just output something like JSON and let it be passed to a database with another tool?
