### ISSUE TITLE
run Firefox in headless mode when scraping

### ISSUE THREAD

**Issue by mscarey** [open-austin/eviction-hearing-parser#33]
This would prevent browser windows from appearing when scraping. Maybe it would be better to have a command line flag to toggle headless mode, because I sometimes look at the browser to debug problems. Defaulting to headless seems reasonable though.

**Comment by jtcasper** [comment]
I've been doing this at the shell level, you just set `MOZ_HEADLESS` to anything, like `MOZ_HEADLESS=1 python parse_hearings.py - < test_input.csv -`

**Comment by mscarey** [comment]
closed by #35
